platform :ios, '9.0'

#inhibit_all_warnings!

use_frameworks!

install! 'cocoapods',
         disable_input_output_paths: true,
         preserve_pod_file_structure: true


target 'ZCCollectionView'  do

  pod 'ZCSwipeView',          :path => '../'

  pod 'ZCCollectionView',     :path => '../'
  
  pod 'ZCLeftTitleButton',    :path => '../'
  
  pod 'ZCMenuView',           :path => '../'

  pod 'ZCMultiLabel',         :path => '../'

end
